# Generated by Django 3.2.7 on 2021-09-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('lecturer', models.CharField(max_length=100)),
                ('online', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=10)),
            ],
        ),
    ]
